version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8018:80'
    depends_on:
      - php
      - swagger
  php:
    build:
      context: .
      dockerfile: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger.yaml