openapi: 3.0.0
info:
  title: 'Catalog'
  version: '0.1'
paths:
  /user/login/:
    post:
      tags:
        - user
      operationId: user_login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Login success'
                  value: { status: 201, data: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTIyMDgxMjYsImV4cCI6MTY1MjIxMTcyNiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJsb2dpbiI6ImFkbWluIn0.CJKBvnHLnovGSpZANpLwdb7kGl4NNPzR7cmfKzv-r7iNCCF2UOstcTTbLaVKe9MfPStk3kj7EClw7D4XGfxbZl58hNjB-DdKNv04s8PfGlEVlcRCAbvgss2Va0gF03fCHGoEvCfUgQqAdyUr1b0zII9ineTzSspbKxmbU2HTCVHgQGwUplVm3z39IZBNRpKGQe1ab1P_A140U4We8UfVid_pMQ3KilGg0VEF80gidzkvD23MgBdAB6O3RbE-w_styQneQRUPzOrNTjtd_42vZpTewwoUivFSboy1geOcDpxSfUYBdW0YZqXCsoVQbA9u_afJyacjSoIC0-0kZyVNVQ }
      security: [ ]
  /user/register/:
    post:
      tags:
        - user
      operationId: user_register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Registration success'
                  value: { status: 201, data: { id: 123, name: test, login: test, email: test, roles: [ ROLE_USER ] } }
      security: [ ]
  /category/create/:
    post:
      tags:
        - category
      operationId: category_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Create category success'
                  value: { status: 201, data: { id: 123, name: test } }
  /category/{id}/:
    get:
      tags:
        - category
      operationId: category_get
      parameters:
        - name: id
          in: path
          description: 'category id'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Get category success'
                  value: { status: 200, data: { id: 123, name: test } }
  /product/{id}/:
    get:
      tags:
        - product
      operationId: product_get
      parameters:
        - name: id
          in: path
          description: 'product id'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Get product success'
                  value: {
                    status: 200,
                    data: {
                      id: 123,
                      name: test,
                      category: {
                        id: 123,
                        name: test
                      },
                      sku: test,
                      price: 123.12,
                      quantity: 123
                    }
                  }
    delete:
      tags:
        - product
      operationId: product_delete
      parameters:
        - name: id
          in: path
          description: 'product id'
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Delete product success'
                  value: {
                    status: 200,
                    data: { }
                  }
  /product/:
    get:
      tags:
        - product
      operationId: product_get_all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Get products success'
                  value: {
                    status: 200,
                    data: [{
                      id: 123,
                      name: test,
                      category: {
                        id: 123,
                        name: test
                      },
                      sku: test,
                      price: 123.12,
                      quantity: 123
                    },{
                      id: 124,
                      name: test2,
                      category: {
                        id: 123,
                        name: test
                      },
                      sku: test4,
                      price: 123.45,
                      quantity: 321
                    }]
                  }
  /product/create/:
    post:
      tags:
        - product
      operationId: product_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Create category success'
                  value: {
                    status: 201,
                    data: {
                      id: 123,
                        name: test,
                        category: {
                          id: 123,
                          name: test
                        },
                        sku: test,
                        price: 123.12,
                        quantity: 123
                    }
                  }
  /product/{id}/edit/:
    post:
      tags:
        - product
      operationId: product_edit
      parameters:
        - name: id
          in: path
          description: 'product id'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditProductDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: { }
              examples:
                Success:
                  summary: 'Edit product success'
                  value: {
                    status: 201,
                    data: {
                      id: 123,
                      name: test,
                      category: {
                        id: 123,
                        name: test
                      },
                      sku: test,
                      price: 123.12,
                      quantity: 123
                    }
                  }
components:
  schemas:
    LoginDto:
      title: 'Login form'
      properties:
        login:
          type: string
        password:
          type: string
          format: password
      type: object
    RegisterDto:
      title: 'Register form'
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
      type: object
    CreateCategoryDto:
      title: 'Create category form'
      properties:
        name:
          type: string
      type: object
    CreateProductDto:
      title: 'Create product form'
      properties:
        name:
          type: string
        categoryId:
          type: integer
        sku:
          type: string
        price:
          type: number
        quantity:
          type: integer
      type: object
    EditProductDto:
      title: 'Edit product form'
      properties:
        name:
          type: string
        categoryId:
          type: integer
        sku:
          type: string
        price:
          type: number
        quantity:
          type: integer
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
security:
  - bearerAuth: [ ]
tags:
  - name: user
    description: 'User methods'
  - name: category
    description: 'Category methods'
  - name: product
    description: 'Product methods'
