openapi: 3.0.0
info:
  title: 'Catalog'
  version: '0.1'
paths:
  /user/login/:
    post:
      tags:
        - user
      operationId: user_login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: {  }
              examples:
                Success:
                  summary: 'Login success'
                  value: { status: 201, data: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTIyMDgxMjYsImV4cCI6MTY1MjIxMTcyNiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJsb2dpbiI6ImFkbWluIn0.CJKBvnHLnovGSpZANpLwdb7kGl4NNPzR7cmfKzv-r7iNCCF2UOstcTTbLaVKe9MfPStk3kj7EClw7D4XGfxbZl58hNjB-DdKNv04s8PfGlEVlcRCAbvgss2Va0gF03fCHGoEvCfUgQqAdyUr1b0zII9ineTzSspbKxmbU2HTCVHgQGwUplVm3z39IZBNRpKGQe1ab1P_A140U4We8UfVid_pMQ3KilGg0VEF80gidzkvD23MgBdAB6O3RbE-w_styQneQRUPzOrNTjtd_42vZpTewwoUivFSboy1geOcDpxSfUYBdW0YZqXCsoVQbA9u_afJyacjSoIC0-0kZyVNVQ }
      security: []
  /user/register/:
    post:
      tags:
        - user
      operationId: user_register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: {  }
              examples:
                Success:
                  summary: 'Registration success'
                  value: { status: 201, data: { id: 123, name: test, login: test, email: test, roles: [ROLE_USER] } }
      security: []
  /category/create/:
    post:
      tags:
        - user
      operationId: category_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryDto'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: {  }
              examples:
                Success:
                  summary: 'Create category success'
                  value: { status: 201, data: { id: 123, name: test} }
components:
  schemas:
    LoginDto:
      title: 'Login form'
      properties:
        login:
          type: string
        password:
          type: string
          format: password
      type: object
    RegisterDto:
      title: 'Register form'
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
      type: object
    CreateCategoryDto:
      title: 'Create category form'
      properties:
        name:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
security:
  -
    bearerAuth: []
tags:
  -
    name: user
    description: 'User methods'
